---
# tasks file for ansible-role-docker
- name: Ensure dependencies are installed
  apt:
    name: "{{ docker_prerequisite_packages }}"
    state: present
    update_cache: true
    force_apt_get: true
- name: Add Docker apt key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
- name: Ensure docker users are added to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
- name: Enabled docker service
  systemd:
    name: docker
    state: started
    enabled: yes
- name: Create custom daemon.json
  template:
    dest: /etc/docker/daemon.json
    src: daemon_json.j2
    mode: 0644
    owner: root
    group: root
  notify:
    - daemon_reload
    - restart_docker
