---
# handlers file for ansible-role-docker
- name: daemon_reload
  systemd:
    daemon_reload: yes
- name: restart_docker
  systemd:
    name: docker
    state: restarted
- name: start_docker
  systemd:
    name: docker
    state: started
    enabled: yes
