---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: bootstrap-ubuntu-focal
    image: ${MOLECULE_DISTRO:-enros/docker-ansible-ubuntu2004:latest}
    command: ${MOLECULE_COMMAND:-/lib/systemd/systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        run_not_in_container: False
verifier:
  name: ansible
