---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: bootstrap-ubuntu-focal
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2004-ansible:latest}
    #dockerfile: Dockerfile.j2
    command: ${MOLECULE_COMMAND:-/lib/systemd/systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
        #- /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static:ro
    tmpfs:
      - /tmp
      - /run
    privileged: yes
    pre_build_image: yes
    #service_manager: ${MOLECULE_SERVICE_MANAGER:-systemd}
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        run_not_in_container: False
verifier:
  name: ansible
